### ISSUE TITLE
openvpn_defer_auth with openvpn-plugin-auth-pam?

### ISSUE THREAD

**Issue by ashleyw-gh** [mozilla-it/openvpn_defer_auth#3]
my current openvpn configuration uses the openvpn options of;
--plugin /config/openvpn-plugin-auth-pam.so vtun0-radius

the openvpn-plugin-auth-pam module stalls while waiting for the MFA prompt.
I attempted to use the 
--setenv deferred_auth_pam 1

option and this did not work as expected, so I stumbled across your openvpn_defer_auth plugin.

Is there a way to use openvpn_defer_auth.so along with openvpn-plugin-auth-pam.so?

I attempted to use;
--plugin /config/openvpn_defer_auth.so /config/openvpn-plugin-auth-pam.so vtun0-radius

but it didn't work and I didn't have a large enough test windows to see what was happening.
Any pointers or advice on easiest way to integrate Radius auth (with upstream MFA) in a non-blocking mode using openvpn CE (in our case VyOS)?

**Comment by gcoxmoz** [comment]
I have no advice here as I haven't integrated it with your module.  If you uncover a bug in this codebase I'm happy to accept a bug report, but I don't have the cycles to triage someone else's module.  Sorry.
